# Generated by Django 4.2.11 on 2024-03-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='twitter_post_url',
            new_name='x_post_url',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='acast_url',
        ),
        migrations.AddField(
            model_name='episode',
            name='apple_podcasts_url',
            field=models.URLField(default='https://podcasts.apple.com/us/podcast/the-sloppy-boys/id1537187838'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='spotify_url',
            field=models.URLField(default='https://open.spotify.com/show/3qFjDCQ16YrjFw5ufNpV3c'),
        ),
    ]
