# Generated by Django 4.2.11 on 2024-03-22 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0002_rename_twitter_post_url_episode_x_post_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='youtube_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
