# Generated by Django 4.2.11 on 2024-04-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0003_episode_youtube_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='filter',
            field=models.BooleanField(default=False),
        ),
    ]
